name: deploy to SSH server
on:  [push]
jobs:

  build-and-deploy:
    name: Build and deploy Gatsby site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.1

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install Project Dependencies
        run: npm install

      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli@2.12.34

      - name: Install additional gatsby dependancies
        run: npm install gatsby-source-graphql gatsby-plugin-image gatsby-plugin-sharp gatsby-source-filesystem gatsby-plugin-mdx gatsby-transformer-sharp


      - name: Build
        run: gatsby build --prefix-paths

      - name: Verify build
        run: ls -la public

      # - name: copy file via ssh key
      #   uses: appleboy/scp-action@v0.1.0
      
      #   with:
      #       host: ${{ secrets.IP }}
      #       username: ${{ secrets.USER }}
      #       key: ${{ secrets.PRIVATE_KEY }}
      #       port: ${{ secrets.PORT }}
      #       source: "./public"
      #       target: "/home/student07/site/html/"
      #       strip_components: 2 # this is important

      # - name: Restart Docker Container
      #   uses: appleboy/ssh-action@v0.1.4
      #   with:
      #     host: ${{ secrets.IP }}
      #     username: ${{ secrets.USER }}
      #     key: ${{ secrets.PRIVATE_KEY }}
      #     port: ${{ secrets.PORT }}
      #     script: |
      #       docker restart student07

      - name: Clear target directory
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            rm -rf /home/student07/site/temp/*
            
      
      - name: Copy files to temporary directory via SSH
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          source: "./public"
          target: "/home/student07/site/temp/"
          strip_components: 2
      
      - name: Move files to the correct directory and start Docker container if necessary
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            rm -rf /home/student07/site/html/*
            mv /home/student07/site/temp/* /home/student07/site/html/
            if [ ! $(docker ps -q -f name=student07) ]; then
              docker start student07
            fi

    
  